config/routes.rb
Uppd::Application.routes.draw do

  devise_scope :admin_user do
    resources :pages
    resources :proceedings
    resources :filings
    resources :doc_pages
  end

  root :to => 'application#index', :via => :get
  match 'page/:id' => 'doc_pages#show', :as => :page
  match '/document_tags/by_dom_id_root/:filing_doc_id/:pagenumber' => 'document_tags#by_dom_id_root', :as => :document_tags_by_dom_id_root
  match '/document_tags/create' => 'document_tags#create', :via => :post, :as => :document_tags_create
  match '/document_tags/update' => 'document_tags#update', :via => :post, :as => :document_tags_update
  match '/document_tags/delete' => 'document_tags#delete', :via => :post, :as => :document_tags_delete

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/filing_doc.rb
class FilingDoc < ActiveRecord::Base
  attr_accessible :filing_doc_id, :doctype, :filetype, :filing_id, :pagecount, :sha1hash, :status, :url
  belongs_to :filing
  has_many :doc_page
  has_many :sections
end

app/controllers/filing_docs_controller.rb
class FilingDocsController < ApplicationController
  before_filter :authenticate_admin_user!, only: [:new, :create, :edit, :save]

  # GET /filing_docs
  # GET /filing_docs.json
  layout "bar_right"
  
  def index
    @filing_docs = FilingDoc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @filing_docs }
    end
  end

  # GET /filing_docs/1
  # GET /filing_docs/1.json
  def show
    @filing_doc = FilingDoc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @filing_doc }
    end
  end

  # GET /filing_docs/new
  # GET /filing_docs/new.json
  def new
    @filing_doc = FilingDoc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @filing_doc }
    end
  end

  # GET /filing_docs/1/edit
  def edit
    @filing_doc = FilingDoc.find(params[:id])
  end

  # POST /filing_docs
  # POST /filing_docs.json
  def create
    @filing_doc = FilingDoc.new(params[:filing_doc])

    respond_to do |format|
      if @filing_doc.save
        format.html { redirect_to @filing_doc, notice: 'Filing doc was successfully created.' }
        format.json { render json: @filing_doc, status: :created, location: @filing_doc }
      else
        format.html { render action: "new" }
        format.json { render json: @filing_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /filing_docs/1
  # PUT /filing_docs/1.json
  def update
    @filing_doc = FilingDoc.find(params[:id])

    respond_to do |format|
      if @filing_doc.update_attributes(params[:filing_doc])
        format.html { redirect_to @filing_doc, notice: 'Filing doc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @filing_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filing_docs/1
  # DELETE /filing_docs/1.json
  def destroy
    @filing_doc = FilingDoc.find(params[:id])
    @filing_doc.destroy

    respond_to do |format|
      format.html { redirect_to filing_docs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/filing_docs_helper.rb
module FilingDocsHelper
end

app/views/filing_docs/_form.html.erb
<%= form_for(@filing_doc) do |f| %>
  <% if @filing_doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filing_doc.errors.count, "error") %> prohibited this filing_doc from being saved:</h2>

      <ul>
      <% @filing_doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filing_docs/edit.html.erb
<h1>Editing filing_doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @filing_doc %> |
<%= link_to 'Back', filing_docs_path %>

app/views/filing_docs/index.html.erb
<h1>Listing filing_docs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @filing_docs.each do |filing_doc| %>
  <tr>
    <td><%= link_to 'Show', filing_doc %></td>
    <td><%= link_to 'Edit', edit_filing_doc_path(filing_doc) %></td>
    <td><%= link_to 'Destroy', filing_doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Filing doc', new_filing_doc_path %>

app/views/filing_docs/new.html.erb
<h1>New filing_doc</h1>

<%= render 'form' %>

<%= link_to 'Back', filing_docs_path %>

app/views/filing_docs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_filing_doc_path(@filing_doc) %> |
<%= link_to 'Back', filing_docs_path %>