config/routes.rb
Uppd::Application.routes.draw do

  devise_scope :admin_user do
    resources :pages
    resources :proceedings
    resources :filings
    resources :doc_pages
  end

  root :to => 'application#index', :via => :get
  match 'page/:id' => 'doc_pages#show', :as => :page
  match '/document_tags/by_dom_id_root/:filing_doc_id/:pagenumber' => 'document_tags#by_dom_id_root', :as => :document_tags_by_dom_id_root
  match '/document_tags/create' => 'document_tags#create', :via => :post, :as => :document_tags_create
  match '/document_tags/update' => 'document_tags#update', :via => :post, :as => :document_tags_update
  match '/document_tags/delete' => 'document_tags#delete', :via => :post, :as => :document_tags_delete

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/filing.rb
class Filing < ActiveRecord::Base
  attr_accessible :applicant, :author, :business_imp, :exparte, :fcc_num, :filing_type, :lawfirm, :posting_date, :proceeding_id, :recv_date
  belongs_to :proceeding
  has_many :filing_docs

  # used to show search criteria and process search queries
  def self.date_metadata
    [
      { label: "After Date", name: :after_date, search_op: "greater_than" },
      { label: "Before Date", name: :before_date, search_op: "less_than" },
    ]
  end
end

app/controllers/filings_controller.rb
class FilingsController < ApplicationController
  before_filter :authenticate_admin_user!, only: [:new, :create, :edit, :save]

  # GET /filings
  # GET /filings.json
  layout "bar_right"

  def index
    @filings = Filing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @filings }
    end
  end

  # GET /filings/1
  # GET /filings/1.json
  def show
    @filing = Filing.find(params[:id])
    # layout 'customlayout'
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @filing }
    end
  end

  # GET /filings/new
  # GET /filings/new.json
  def new
    @filing = Filing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @filing }
    end
  end

  # GET /filings/1/edit
  def edit
    @filing = Filing.find(params[:id])
  end

  # POST /filings
  # POST /filings.json
  def create
    @filing = Filing.new(params[:filing])

    respond_to do |format|
      if @filing.save
        format.html { redirect_to @filing, notice: 'Filing was successfully created.' }
        format.json { render json: @filing, status: :created, location: @filing }
      else
        format.html { render action: "new" }
        format.json { render json: @filing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /filings/1
  # PUT /filings/1.json
  def update
    @filing = Filing.find(params[:id])

    respond_to do |format|
      if @filing.update_attributes(params[:filing])
        format.html { redirect_to @filing, notice: 'Filing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @filing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filings/1
  # DELETE /filings/1.json
  def destroy
    @filing = Filing.find(params[:id])
    @filing.destroy

    respond_to do |format|
      format.html { redirect_to filings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/filings_helper.rb
module FilingsHelper
end

app/views/filings/_form.html.erb
<%= form_for(@filing) do |f| %>
  <% if @filing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filing.errors.count, "error") %> prohibited this filing from being saved:</h2>

      <ul>
      <% @filing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filings/edit.html.erb
<h1>Editing filing</h1>

<%= render 'form' %>

<%= link_to 'Show', @filing %> |
<%= link_to 'Back', filings_path %>

app/views/filings/index.html.erb
<h1>Listing filings</h1>

<table>
  <tr>
    <th>Proceeding Id</th>
    <th>Type</th>
    <th>Receive Date</th>
    <th>Author</th>
    <th>View</th>
  </tr>

<% @filings.each do |filing| %>
  <tr>
    <td><%= filing.proceeding_id %></td>
    <td><%= filing.filing_type %></td>
    <td><%= filing.recv_date.strftime("%m/%d/%Y") %></td>
    <td><%= filing.author %></td>
    <td><%= link_to "Show", filing_path(filing) %></td>
  </tr>
<% end %>
</table>

app/views/filings/new.html.erb
<h1>New filing</h1>

<%= render 'form' %>

<%= link_to 'Back', filings_path %>

app/views/filings/show.html.erb
<%= @filing.author %>
<hr>
<%= @filing.recv_date %>
<hr>
<%= link_to 'Edit', edit_filing_path(@filing) %> |
<%= link_to 'Back', filings_path %>

<%= content_for :sidebar_right do %>
	<h2>Author</h2>
	<%= @filing.author %>
<% end %>