config/routes.rb
Uppd::Application.routes.draw do

  devise_scope :admin_user do
    resources :pages
    resources :proceedings
    resources :filings
    resources :doc_pages
  end

  root :to => 'application#index', :via => :get
  match 'page/:id' => 'doc_pages#show', :as => :page
  match '/document_tags/by_dom_id_root/:filing_doc_id/:pagenumber' => 'document_tags#by_dom_id_root', :as => :document_tags_by_dom_id_root
  match '/document_tags/create' => 'document_tags#create', :via => :post, :as => :document_tags_create
  match '/document_tags/update' => 'document_tags#update', :via => :post, :as => :document_tags_update
  match '/document_tags/delete' => 'document_tags#delete', :via => :post, :as => :document_tags_delete

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.body %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<% provide(:title, @page.title) %>
<p id="notice"><%= notice %></p>

<h2><%= @page.title %></h2>

<%= simple_format @page.body %>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>