config/routes.rb
Uppd::Application.routes.draw do

  devise_scope :admin_user do
    resources :pages
    resources :proceedings
    resources :filings
    resources :doc_pages
  end

  root :to => 'application#index', :via => :get
  match 'page/:id' => 'doc_pages#show', :as => :page
  match '/document_tags/by_dom_id_root/:filing_doc_id/:pagenumber' => 'document_tags#by_dom_id_root', :as => :document_tags_by_dom_id_root
  match '/document_tags/create' => 'document_tags#create', :via => :post, :as => :document_tags_create
  match '/document_tags/update' => 'document_tags#update', :via => :post, :as => :document_tags_update
  match '/document_tags/delete' => 'document_tags#delete', :via => :post, :as => :document_tags_delete

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/proceeding.rb
class Proceeding < ActiveRecord::Base
  attr_accessible :number, :status
  has_many :filings
end

app/controllers/proceedings_controller.rb
class ProceedingsController < ApplicationController
  before_filter :authenticate_admin_user!, only: [:new, :create, :edit, :save]

  # GET /proceedings
  # GET /proceedings.json
  def index
    @proceedings = Proceeding.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proceedings }
    end
  end

  # GET /proceedings/1
  # GET /proceedings/1.json
  def show
    @proceeding = Proceeding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proceeding }
    end
  end

  # GET /proceedings/new
  # GET /proceedings/new.json
  def new
    @proceeding = Proceeding.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proceeding }
    end
  end

  # GET /proceedings/1/edit
  def edit
    @proceeding = Proceeding.find(params[:id])
  end

  # POST /proceedings
  # POST /proceedings.json
  def create
    @proceeding = Proceeding.new(params[:proceeding])

    respond_to do |format|
      if @proceeding.save
        format.html { redirect_to @proceeding, notice: 'Proceeding was successfully created.' }
        format.json { render json: @proceeding, status: :created, location: @proceeding }
      else
        format.html { render action: "new" }
        format.json { render json: @proceeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proceedings/1
  # PUT /proceedings/1.json
  def update
    @proceeding = Proceeding.find(params[:id])

    respond_to do |format|
      if @proceeding.update_attributes(params[:proceeding])
        format.html { redirect_to @proceeding, notice: 'Proceeding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proceeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proceedings/1
  # DELETE /proceedings/1.json
  def destroy
    @proceeding = Proceeding.find(params[:id])
    @proceeding.destroy

    respond_to do |format|
      format.html { redirect_to proceedings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proceedings_helper.rb
module ProceedingsHelper
end

app/views/proceedings/_form.html.erb
<%= form_for(@proceeding) do |f| %>
  <% if @proceeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proceeding.errors.count, "error") %> prohibited this proceeding from being saved:</h2>

      <ul>
      <% @proceeding.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proceedings/edit.html.erb
<h1>Editing proceeding</h1>

<%= render 'form' %>

<%= link_to 'Show', @proceeding %> |
<%= link_to 'Back', proceedings_path %>

app/views/proceedings/index.html.erb
<h1>Listing proceedings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proceedings.each do |proceeding| %>
  <tr>
    <td><%= link_to 'Show', proceeding %></td>
    <td><%= link_to 'Edit', edit_proceeding_path(proceeding) %></td>
    <td><%= link_to 'Destroy', proceeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Proceeding', new_proceeding_path %>

app/views/proceedings/new.html.erb
<h1>New proceeding</h1>

<%= render 'form' %>

<%= link_to 'Back', proceedings_path %>

app/views/proceedings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_proceeding_path(@proceeding) %> |
<%= link_to 'Back', proceedings_path %>